spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

hystrix:
  command:
    authors:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    books:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    comments:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    genres:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
#logging:
#  level:
#    ROOT: ERROR