spring:
  data:
    mongodb:
      #      uri: mongodb://localhost:27012/library
      #      uri: localhost
      #      port: 27017
      database: library
#      authentication-database: admin
#      username: root
#      password: root

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - otus.orm.exp.changelog

#logging:
#  level:
#    ROOT: ERROR